### ISSUE TITLE
Exception is throwing while expected result is less then 0 

### ISSUE THREAD

**Issue by yenalyev** [yenalyev/Calculator#1]
expression: 1-2
expected: -1.0
actual: 
DelimiterPosition{position=1, delimiter=MINUS}
DelimiterPosition{position=0, delimiter=MINUS}
Exception in thread "main" java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.base/java.lang.StringLatin1.charAt(StringLatin1.java:44)
	at java.base/java.lang.String.charAt(String.java:692)
	at logic.CalculationUtils.calculate(CalculationUtils.java:19)
	at run.Runner.runMostPriorityOperation(Runner.java:24)
	at run.Runner.run(Runner.java:33)
	at main.Main.main(Main.java:16)

**Comment by yenalyev** [comment]
expression: 1-2
expected: -1.0
actual: -1.0

expression: -1*-2
expected: 2.0
actual: 2.0
